name: ap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  firebase_app_check: ^0.3.1+3
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/images/icon.png"

flutter:
  assets:
    - assets/images/
  uses-material-design: true
