// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEbRjddy-9VOeFWadzcaeQuENj_Kc0mgI',
    appId: '1:766496516073:web:b6c8c091c0d352caba0d78',
    messagingSenderId: '766496516073',
    projectId: 'athp-779ea',
    authDomain: 'athp-779ea.firebaseapp.com',
    storageBucket: 'athp-779ea.firebasestorage.app',
    measurementId: 'G-955146H928',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOVpuOz-SO_bTiZr7FzYUEI3BKdg6tr-U',
    appId: '1:766496516073:android:44f68811bb3953f9ba0d78',
    messagingSenderId: '766496516073',
    projectId: 'athp-779ea',
    storageBucket: 'athp-779ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsHMSbrMWpPVfTbMPqHeRyc0jn9Y2evHw',
    appId: '1:766496516073:ios:f156e36d98e7f1aeba0d78',
    messagingSenderId: '766496516073',
    projectId: 'athp-779ea',
    storageBucket: 'athp-779ea.firebasestorage.app',
    iosBundleId: 'com.example.ap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsHMSbrMWpPVfTbMPqHeRyc0jn9Y2evHw',
    appId: '1:766496516073:ios:f156e36d98e7f1aeba0d78',
    messagingSenderId: '766496516073',
    projectId: 'athp-779ea',
    storageBucket: 'athp-779ea.firebasestorage.app',
    iosBundleId: 'com.example.ap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEbRjddy-9VOeFWadzcaeQuENj_Kc0mgI',
    appId: '1:766496516073:web:652399d31efb078bba0d78',
    messagingSenderId: '766496516073',
    projectId: 'athp-779ea',
    authDomain: 'athp-779ea.firebaseapp.com',
    storageBucket: 'athp-779ea.firebasestorage.app',
    measurementId: 'G-3RJD861W1G',
  );
}
